#!/bin/bash
# machine2-setup.sh - Streaming Server Setup Script

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Default values
BUILD_ONLY=false
PROJECT_DIR="/opt/fall-detection-streaming"
PROJECT_NAME="FallDetection.Streaming"
SERVICE_NAME="fall-detection-streaming"
SRS_SERVICE_NAME="srs-server"
PORT=8000
RTMP_PORT=1935

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --build-only)
      BUILD_ONLY=true
      shift
      ;;
    --project-dir)
      PROJECT_DIR="$2"
      shift 2
      ;;
    --setup-turn)
      SETUP_TURN=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--build-only] [--project-dir /path/to/project] [--setup-turn]"
      exit 1
      ;;
  esac
done

echo -e "${GREEN}=== Fall Detection Streaming Server Setup ===${NC}"

# TURN-only setup mode
if [ "$SETUP_TURN" = true ]; then
  echo -e "${YELLOW}=== TURN Server Only Setup Mode ===${NC}"
  
  # Install Coturn TURN server
  echo -e "${YELLOW}Step 1: Installing Coturn TURN server...${NC}"
  sudo apt-get update
  sudo apt-get install -y coturn
  
  # Create turnserver configuration
  echo -e "${YELLOW}Step 2: Configuring TURN server...${NC}"
  sudo tee /etc/turnserver.conf > /dev/null <<EOF
# Coturn TURN Server Configuration
# Generated by Fall Detection Streaming Server setup

# Listening port
listening-port=3478
tls-listening-port=5349

# Server name
server-name=$(hostname -f)

# Realm for authentication
realm=fall-detection-streaming

# Use fingerprint in TURN responses
fingerprint

# Use authentication
use-auth-secret

# Static authentication secret (generate a secure secret in production)
static-auth-secret=change_this_to_a_secure_secret_in_production

# Certificate files (uncomment and set paths for production TLS)
# cert=/etc/coturn/cert.pem
# pkey=/etc/coturn/privkey.pem

# Default realm
default-realm=fall-detection-streaming

# No loopback preference
no-loopback-peers
no-multicast-peers

# Enable UDP relay
udp-relay

# Enable WebSocket support
# web-socket-all

# Log file
log-file=/var/log/turnserver.log

# Verbose logging (comment out for production)
# verbose

# Disable specific IPs (uncomment to restrict)
# no-stun-bind-ip=127.0.0.1
EOF
  
  # Create systemd service file for Coturn
  echo -e "${YELLOW}Step 3: Creating turnserver.service...${NC}"
  sudo cp $PROJECT_DIR/turnserver.service /etc/systemd/system/
  
  # Create systemd service override for Coturn
  echo -e "${YELLOW}Step 4: Setting up systemd service override...${NC}"
  sudo mkdir -p /etc/systemd/system/turnserver.service.d
  sudo tee /etc/systemd/system/turnserver.service.d/override.conf > /dev/null <<EOF
[Service]
User=$USER
Group=$USER
RuntimeDirectory=turnserver
RuntimeDirectoryMode=0755
LogsDirectory=turnserver
StateDirectory=turnserver
EOF
  
  # Create turnserver user and group if needed
  if ! id turnserver &>/dev/null; then
    sudo useradd -r -s /sbin/nologin turnserver 2>/dev/null || true
  fi
  
  # Create required directories
  sudo mkdir -p /var/run/turnserver
  sudo chown turnserver:turnserver /var/run/turnserver
  sudo touch /var/log/turnserver.log
  sudo chown turnserver:turnserver /var/log/turnserver.log
  
  # Configure firewall
  echo -e "${YELLOW}Step 5: Configuring firewall...${NC}"
  sudo ufw allow 3478/udp   # TURN
  sudo ufw allow 3478/tcp   # TURN
  sudo ufw allow 5349/tcp   # TURN TLS
  sudo ufw reload
  
  # Start and enable service
  echo -e "${YELLOW}Step 6: Starting TURN server...${NC}"
  sudo systemctl daemon-reload
  sudo systemctl enable turnserver
  sudo systemctl start turnserver
  
  # Verify status
  echo -e "${YELLOW}Step 7: Verifying TURN server status...${NC}"
  if sudo systemctl is-active --quiet turnserver; then
    echo -e "${GREEN}TURN server is running successfully on port 3478${NC}"
  else
    echo -e "${YELLOW}TURN server installed but may need more time to start${NC}"
    sudo systemctl status turnserver --no-pager
  fi
  
  echo -e "${GREEN}=== TURN Server Setup Complete! ===${NC}"
  echo -e "TURN server: $(hostname -I | awk '{print $1}'):3478 (for WebRTC NAT traversal)"
  echo -e "TURN TLS: $(hostname -I | awk '{print $1}'):5349"
  echo -e ""
  echo -e "Useful commands:"
  echo -e "  Check status: sudo systemctl status turnserver"
  echo -e "  View logs: sudo journalctl -u turnserver -f"
  echo -e "  Restart: sudo systemctl restart turnserver"
  echo -e "  Stop: sudo systemctl stop turnserver"
  
  exit 0
fi

if [ "$BUILD_ONLY" = false ]; then
  echo -e "${YELLOW}Step 1: Installing system dependencies...${NC}"
  
  # Update system
  sudo apt-get update
  sudo apt-get upgrade -y
  
  # Install .NET 8 SDK
  echo -e "${YELLOW}Installing .NET 8 SDK...${NC}"
  wget https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  sudo dpkg -i packages-microsoft-prod.deb
  rm packages-microsoft-prod.deb
  sudo apt-get update
  sudo apt-get install -y dotnet-sdk-8.0
  
  # Install SRS dependencies
  sudo apt-get install -y build-essential git libssl-dev zlib1g-dev libpcre3-dev
  
  echo -e "${YELLOW}Step 2: Installing SRS 6.0-r0 (RTMP/WebRTC server)...${NC}"
  
  # Download and build SRS from source
  cd /tmp
  wget -q https://github.com/ossrs/srs/releases/download/v6.0-r0/srs-server-6.0-r0.tar.gz
  tar -xzf srs-server-6.0-r0.tar.gz
  cd srs-server-6.0-r0/trunk/
  
  # Build SRS
  ./configure --with-ffmpeg --with-hls --with-ssl --with-http-callback
  make -j$(nproc)
  
  # Install SRS
  sudo cp objs/srs /usr/local/bin/
  sudo mkdir -p /usr/local/srs/conf
  sudo cp conf/srs.conf /usr/local/srs/conf/
  
  # Create SRS configuration for WebRTC
  sudo tee /usr/local/srs/conf/srs.conf > /dev/null <<EOF
listen 1935;
max_connections 1000;
daemon off;

http_api {
    enabled on;
    listen 1985;
}

http_server {
    enabled on;
    listen 8080;
}

rtc_server {
    enabled on;
    listen 8000;
    candidate \$CANDIDATE;
}

vhost __defaultVhost__ {
    rtc {
        enabled on;
        rtc_to_rtmp on;
        rtmp_to_rtc on;
    }
    
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
}
EOF
  
  # Create SRS systemd service
  sudo tee /etc/systemd/system/$SRS_SERVICE_NAME.service > /dev/null <<EOF
[Unit]
Description=SRS Streaming Server (RTMP/WebRTC)
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=/usr/local/srs
ExecStart=/usr/local/bin/srs -c /usr/local/srs/conf/srs.conf
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  
  # Create turnserver.service file for Coturn
  echo -e "${YELLOW}Step 2b: Creating turnserver.service...${NC}"
  sudo cp $PROJECT_DIR/turnserver.service /etc/systemd/system/
  
  echo -e "${YELLOW}Step 2c: Installing Coturn TURN server for WebRTC NAT traversal...${NC}"
  
  # Install Coturn TURN server
  sudo apt-get install -y coturn
  
  # Create turnserver configuration
  sudo tee /etc/turnserver.conf > /dev/null <<EOF
# Coturn TURN Server Configuration
# Generated by Fall Detection Streaming Server setup

# Listening port
listening-port=3478
tls-listening-port=5349

# Server name
server-name=$(hostname -f)

# Realm for authentication
realm=fall-detection-streaming

# Use fingerprint in TURN responses
fingerprint

# Use authentication
use-auth-secret

# Static authentication secret (generate a secure secret in production)
static-auth-secret=change_this_to_a_secure_secret_in_production

# Certificate files (uncomment and set paths for production TLS)
# cert=/etc/coturn/cert.pem
# pkey=/etc/coturn/privkey.pem

# Default realm
default-realm=fall-detection-streaming

# No loopback preference
no-loopback-peers
no-multicast-peers

# Enable UDP relay
udp-relay

# Enable WebSocket support
# web-socket-all

# Log file
log-file=/var/log/turnserver.log

# Verbose logging (comment out for production)
# verbose

# Disable specific IPs (uncomment to restrict)
# no-stun-bind-ip=127.0.0.1
EOF
  
  # Create systemd service override for Coturn
  echo -e "${YELLOW}Step 2d: Setting up systemd service override...${NC}"
  sudo mkdir -p /etc/systemd/system/turnserver.service.d
  sudo tee /etc/systemd/system/turnserver.service.d/override.conf > /dev/null <<EOF
[Service]
User=$USER
Group=$USER
RuntimeDirectory=turnserver
RuntimeDirectoryMode=0755
LogsDirectory=turnserver
StateDirectory=turnserver
EOF
  
  # Create turnserver user and group if needed
  if ! id turnserver &>/dev/null; then
    sudo useradd -r -s /sbin/nologin turnserver 2>/dev/null || true
  fi
  
  # Create required directories
  sudo mkdir -p /var/run/turnserver
  sudo chown turnserver:turnserver /var/run/turnserver
  sudo touch /var/log/turnserver.log
  sudo chown turnserver:turnserver /var/log/turnserver.log
  
  echo -e "${YELLOW}Step 3: Creating project structure...${NC}"
  
  # Create project directory
  sudo mkdir -p $PROJECT_DIR
  sudo chown -R $USER:$USER $PROJECT_DIR
  
  # Navigate to project directory
  cd $PROJECT_DIR
  
  # Create .NET project
  echo -e "${YELLOW}Creating ASP.NET Core MVC project...${NC}"
  dotnet new mvc -n $PROJECT_NAME --framework net8.0
  
  # Navigate into project
  cd $PROJECT_NAME
  
  echo -e "${YELLOW}Step 4: Configuring firewall...${NC}"
  sudo ufw allow $PORT/tcp
  sudo ufw allow $RTMP_PORT/tcp
  sudo ufw allow 8000/udp  # WebRTC
  sudo ufw allow 3478/udp   # TURN
  sudo ufw allow 3478/tcp   # TURN
  sudo ufw allow 5349/tcp   # TURN TLS
  sudo ufw allow ssh
  sudo ufw --force enable
  
  echo -e "${YELLOW}Step 5: Creating data directories...${NC}"
  sudo mkdir -p /var/lib/fall-detection/streaming
  sudo mkdir -p /var/log/fall-detection/streaming
  sudo mkdir -p /var/www/fall-detection/recordings
  sudo chown -R $USER:$USER /var/lib/fall-detection /var/log/fall-detection /var/www/fall-detection
  
  echo -e "${YELLOW}Step 6: Creating ASP.NET systemd service...${NC}"
  sudo tee /etc/systemd/system/$SERVICE_NAME.service > /dev/null <<EOF
[Unit]
Description=Fall Detection Streaming Server
After=network.target $SRS_SERVICE_NAME.service

[Service]
Type=exec
User=$USER
WorkingDirectory=$PROJECT_DIR/$PROJECT_NAME
ExecStart=/usr/bin/dotnet run --urls http://0.0.0.0:$PORT
Restart=always
RestartSec=10
KillSignal=SIGINT
Environment="ASPNETCORE_ENVIRONMENT=Production"
Environment="DOTNET_PRINT_TELEMETRY_MESSAGE=false"

[Install]
WantedBy=multi-user.target
EOF
  
  sudo systemctl daemon-reload
else
  echo -e "${YELLOW}[BUILD-ONLY MODE] Skipping system setup, going directly to build...${NC}"
  
  # Navigate to project directory
  echo "Navigating to project directory: $PROJECT_DIR/$PROJECT_NAME"
  cd "$PROJECT_DIR/$PROJECT_NAME" || {
    echo -e "${RED}Error: Could not navigate to $PROJECT_DIR/$PROJECT_NAME${NC}"
    echo "Make sure the project exists or specify --project-dir with the correct path"
    exit 1
  }
  
  # Verify we're in the project directory
  if [ ! -f "FallDetection.Streaming.csproj" ]; then
    echo -e "${RED}Error: Not in project directory. FallDetection.Streaming.csproj not found${NC}"
    echo "Current directory: $(pwd)"
    exit 1
  fi
fi

echo -e "${YELLOW}Step 7: Building and publishing the project...${NC}"
echo "Current directory: $(pwd)"

# Build the project

# Backup existing Data directory BEFORE deleting publish folder
echo "Backing up existing publish/Data/ to ./backup/Data/..."
if [ -d "./publish/Data" ]; then
  mkdir -p ./backup/Data/
  cp -r ./publish/Data/* ./backup/Data/
  echo "Data directory backed up"
fi

# Clean up existing publish directory to prevent nested publish/publish/... folders
if [ -d "./publish" ]; then
  echo "Removing existing publish directory to prevent nested builds..."
  rm -rf ./publish
fi

# Restore NuGet packages
echo "Restoring NuGet packages..."
dotnet restore

echo "Building project..."
dotnet build --configuration Release --no-restore

echo "Publishing project..."
dotnet publish --configuration Release --no-build --output ./publish

# Restore Data directory to new publish folder
echo "Restoring backup to ./publish/Data/..."
if [ -d "./backup/Data" ] && [ "$(ls -A ./backup/Data 2>/dev/null)" ]; then
  mkdir -p ./publish/Data/
  cp -r ./backup/Data/* ./publish/Data/
  echo -e "${GREEN}Data directory restored to publish folder${NC}"
fi

echo -e "${YELLOW}Step 8: Updating systemd services for published apps...${NC}"

# Update ASP.NET service
sudo tee /etc/systemd/system/$SERVICE_NAME.service > /dev/null <<EOF
[Unit]
Description=Fall Detection Streaming Server
After=network.target $SRS_SERVICE_NAME.service

[Service]
Type=exec
User=$USER
WorkingDirectory=$PROJECT_DIR/$PROJECT_NAME/publish
ExecStart=/usr/bin/dotnet FallDetection.Streaming.dll --urls http://0.0.0.0:$PORT
Restart=always
RestartSec=10
KillSignal=SIGINT
Environment="ASPNETCORE_ENVIRONMENT=Production"
Environment="DOTNET_PRINT_TELEMETRY_MESSAGE=false"

[Install]
WantedBy=multi-user.target
EOF

if [ "$BUILD_ONLY" = false ]; then
  echo -e "${YELLOW}Step 9: Starting services...${NC}"
  sudo systemctl daemon-reload
  
  # Start Coturn first (TURN server for WebRTC)
  echo -e "${YELLOW}Starting Coturn TURN server...${NC}"
  sudo systemctl enable turnserver
  sudo systemctl start turnserver
  
  # Start SRS
  sudo systemctl enable $SRS_SERVICE_NAME
  sudo systemctl start $SRS_SERVICE_NAME
  
  # Start ASP.NET app
  sudo systemctl enable $SERVICE_NAME
  sudo systemctl start $SERVICE_NAME
  
  echo -e "${YELLOW}Step 10: Verifying services status...${NC}"
  echo -e "${YELLOW}Coturn TURN Server Status:${NC}"
  sudo systemctl status turnserver --no-pager
  echo -e "${YELLOW}SRS Server Status:${NC}"
  sudo systemctl status $SRS_SERVICE_NAME --no-pager
  echo -e "\n${YELLOW}ASP.NET Server Status:${NC}"
  sudo systemctl status $SERVICE_NAME --no-pager
  
  # Test the endpoints
  echo -e "${YELLOW}Step 11: Testing endpoints...${NC}"
  sleep 5
  echo "Testing web interface..."
  curl -f http://localhost:$PORT || echo -e "${RED}Web interface check failed${NC}"
  
  echo "Testing SRS API..."
  curl -f http://localhost:1985/api/v1/versions || echo -e "${YELLOW}SRS API check failed (might need more time to start)${NC}"
  
  echo "Testing TURN server..."
  if sudo systemctl is-active --quiet turnserver; then
    echo -e "${GREEN}TURN server is running on port 3478${NC}"
  else
    echo -e "${YELLOW}TURN server check failed (might need more time to start)${NC}"
  fi
  
  echo -e "${GREEN}=== Setup Complete! ===${NC}"
  echo -e "Streaming Server is running on: http://$(hostname -I | awk '{print $1}'):$PORT"
  echo -e "RTMP ingest: rtmp://$(hostname -I | awk '{print $1}'):$RTMP_PORT/live/[camera_id]"
  echo -e "TURN server: $(hostname -I | awk '{print $1}'):3478 (for WebRTC NAT traversal)"
  echo -e "Services status:"
  echo -e "  Coturn: sudo systemctl status turnserver"
  echo -e "  SRS: sudo systemctl status $SRS_SERVICE_NAME"
  echo -e "  Web: sudo systemctl status $SERVICE_NAME"
  echo -e "Logs:"
  echo -e "  Coturn: sudo journalctl -u turnserver -f"
  echo -e "  SRS: sudo journalctl -u $SRS_SERVICE_NAME -f"
  echo -e "  Web: sudo journalctl -u $SERVICE_NAME -f"
else
  echo -e "${GREEN}=== Build Complete! ===${NC}"
  echo -e "Project published to: $PROJECT_DIR/$PROJECT_NAME/publish"
  echo -e "Current directory: $(pwd)"
  echo -e "To start the services manually:"
  echo -e "  sudo systemctl daemon-reload"
  echo -e "  sudo systemctl enable turnserver"
  echo -e "  sudo systemctl enable $SRS_SERVICE_NAME $SERVICE_NAME"
  echo -e "  sudo systemctl start turnserver"
  echo -e "  sudo systemctl start $SRS_SERVICE_NAME"
  echo -e "  sudo systemctl start $SERVICE_NAME"
fi
